<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta name="generator" content="pandoc" />



<title>5: Populations hierarchies: subsetting and clone correction</title>

<script src="libs/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="libs/bootstrap-2.3.2/css/readable.min.css" rel="stylesheet" />
<link href="libs/bootstrap-2.3.2/css/bootstrap-responsive.min.css" rel="stylesheet" />
<script src="libs/bootstrap-2.3.2/js/bootstrap.min.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52691601-2', 'auto');
  ga('send', 'pageview');

</script>

<style type="text/css">

/* padding for bootstrap navbar */
body {
  padding-top: 50px;
  padding-bottom: 40px;
  padding-right: 50px;
  padding-left: -50px;
}
@media (max-width: 979px) {
  body {
    padding-top: 0;
  }
}

/* offset scroll position for anchor links (for fixed navbar)  */
@media (min-width: 980px) {
  .section h2 {
    padding-top: 52px;
    margin-top: -52px;
  }
  .section h3 {
    padding-top: 52px;
    margin-top: -52px;
  }
}


/* don't use link color in navbar */
.dropdown-menu>li>a {
  color: black;
}

</style>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="libs/highlight/default.css"
      type="text/css" />
<script src="libs/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
</style>
<div class="container-fluid main-container">


<div class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="index.html"><b>Population Genetics in R</b></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="dropdown">
            <a href="chapters" class="dropdown-toggle" data-toggle="dropdown">Chapters<b class="caret"></b></a>
            <ul class="dropdown-menu">
               <li><a href="Preface.html">i. Preface</a></li>
               <li><a href="C01_Introduction.html">1. Introduction</a></li>
               <li><a href="C02_Getting_ready_to_use_R.html">2. Getting ready to use R</a></li>
               <li><a href="C03_Data_Preparation.html">3. Data preparation</a></li>
               <li><a href="C04_First_Steps.html">4. First steps</a></li>
               <li><a href="C05_Population_Hierarchies.html">5. Population hierarchies and clone correction</a></li>
               <li><a href="C06_Locus_Stats.html">6. Locus-based statistics and missing data</a></li>
               <li><a href="C07_Genotypic_EvenRichDiv.html">7. Genotypic evenness, richness, and diversity</a></li>
               <li><a href="C08_Linkage_disequilibrium.html">8. Linkage disequilibrium</a></li>
               <li><a href="C09_Pop_Structure.html">9. Population structure</a></li>
               <li><a href="C10_AMOVA.html">10. AMOVA</a></li>
               <li><a href="C11_DAPC.html">11. Discriminant analysis of principal components (DAPC)</a></li>
               </ul>
            </li>
          <li class="dropdown">
            <a href="appendices" class="dropdown-toggle" data-toggle="dropdown">Appendices<b class="caret"></b></a>
            <ul class = "dropdown-menu">
               <li><a href="A1_Data_sets.html">A1. Data sets</a></li>
               <li><a href="A2_Function_Glossary.html">A2. Function glossary</a></li>
            </ul>
          </li>
          
        <ul class="nav">
          <li><a href="Authors.html">About</a></li>
          <li class="dropdown">

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
<div class="row">
<div class="span10 offset1">

<div id="header">
<h1 class="title">5: Populations hierarchies: subsetting and clone correction</h1>
</div>

<div id="TOC">
<ul>
<li><a href="#data-used-in-this-example">Data used in this example</a></li>
<li><a href="#working-with-hierarchical-data">Working with hierarchical data</a></li>
<li><a href="#importing-data-labeled-according-to-a-hierarchy">Importing data labeled according to a hierarchy</a></li>
<li><a href="#assigning-hierarchical-levels">Assigning hierarchical levels</a></li>
<li><a href="#clone-correction">Clone correction</a></li>
<li><a href="#conclusions">Conclusions</a></li>
<li><a href="#references">References</a></li>
</ul>
</div>

<p>Populations are best sampled hierarchically on a range of scales from subpopulations (e.g. fields, valleys, ranges) to regions (e.g. valleys, states, countries or continents) or across time (years or decades). This approach is useful because population structure and evolutionary processes may not be discernible <em>a priori</em>. Most of the times we do not know if population are differentiated locally, regionally or globally or in time. Thus, a combination of targeted local sampling with sampling over larger spatial or temporal scales is necessary to detect population structure over different scales, without using intense sampling throughout the entire range.</p>
<p>The methods implemented in <em>poppr</em> allow specification of which hierarchies you want to analyze. This is a rapid way of working with subsets of your data without having to perform any data manipulation or changing the input file. In this tutorial, we will show you how to define the hierarchical structure of your data and how to specify specific levels that you might want to analyze.</p>
<div id="data-used-in-this-example" class="section level2">
<h2>Data used in this example</h2>
<p>For this example, we will use the <code>monpop</code> data set <span class="citation">(Everhart &amp; Scherm, 2014)</span>. This microsatellite data consists of 13 loci for 694 individuals of the haploid fungal pathogen <em>Monilinia fructicola</em> that infects peach flowers and fruits in commercial orchards. The monpop population came from four trees within a single orchard (trees 26, 45, and 7). Each tree was sampled in 2009, 2010, and/or 2011. Additionally, each sample was noted as to whether it came from a blossom or a fruit. This example data set is included with the <em>poppr</em> package.</p>
</div>
<div id="working-with-hierarchical-data" class="section level2">
<h2>Working with hierarchical data</h2>
<p>The steps for working with hierarchical data include:</p>
<ol style="list-style-type: decimal">
<li>Import data set with samples labeled according to hierarchy</li>
<li>Define the hierarchical levels for the data</li>
<li>Setting the hierarchical level(s) that you want to have analyzed</li>
</ol>
</div>
<div id="importing-data-labeled-according-to-a-hierarchy" class="section level2">
<h2>Importing data labeled according to a hierarchy</h2>
<p>The easiest way to work with hierarchical data is to label each sample using an underscore “_” to separate each hierarchical level. This was already done for the monpop data, where each sample was coded hierarchically by tree, year, and symptom in the following format: “Tree_Year_Symptom”.</p>
<p>Let’s load the hierarchically labeled example data:</p>
<pre class="r"><code>library(poppr)
data(monpop)
monpop</code></pre>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      1 hierarchical level - Pop
##     12 populations defined - 7_09_BB 26_09_BB 26_09_FR ... 45_10_FR 
## 26_11_BB 26_11_FR</code></pre>
<p><strong>Genotype information</strong> shows us that the data contains 264 multilocus genotypes among 694 haploid individuals with 13 loci. <strong>Population information</strong> has two items, the hierarchical levels and the populations defined. You can think of hierarchical levels as the index names for each of the hierarchical levels within your data (so for our data it should be Tree, Year, and Symptom). By default, however, no hierarchical levels are defined and so this is “Pop”, which is the entire dataset of 694 individuals. Because we labeled each sample according to hierarchical level, populations defined shows us our data has 12 groups defined: 7_09_BB, 26_09_BB, 26_09_FR, 7_09_FR, 26_10_BB, 45_10_BB, 79_10_BB, 79_10_FR, 26_10_FR, 45_10_FR, 26_11_BB, 26_11_FR.</p>
</div>
<div id="assigning-hierarchical-levels" class="section level2">
<h2>Assigning hierarchical levels</h2>
<p>We imported the data that has three hierarchical levels “Tree_Year_Symptom”. In order to analyze our data according to any combination of those three hierarchical levels, we need to tell <em>poppr</em> that the 12 groups should be split by tree, year, and/or symptom. Thus, the first step is to split our data according to hierarchy so that we can access each of the three hierarchical levels in the data. The <code>splithierarchy</code> command is used to index the three hierarchical levels:</p>
<pre class="r"><code>splithierarchy(monpop) &lt;- ~Tree/Year/Symptom
monpop</code></pre>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      3 hierarchical levels - Tree Year Symptom
##     12 populations defined - 7_09_BB 26_09_BB 26_09_FR ... 45_10_FR 
## 26_11_BB 26_11_FR</code></pre>
<p>After splitting the data populations are specified by hierarchical level: “Tree Year Symptom”.</p>
<p>Next, we analyze the data according to Tree and Year:</p>
<pre class="r"><code>setpop(monpop) &lt;- ~Tree/Year
monpop</code></pre>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      3 hierarchical levels - Tree Year Symptom
##      6 populations defined - 7_9 26_9 26_10 45_10 79_10 26_11</code></pre>
<p>To analyze the data according to Symptom:</p>
<pre class="r"><code>setpop(monpop) &lt;- ~Symptom
monpop</code></pre>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      3 hierarchical levels - Tree Year Symptom
##      2 populations defined - BB FR</code></pre>
<p>Order of the levels that you define is important, so if we wanted to define the symptoms according to tree, we would use the following:</p>
<pre class="r"><code>setpop(monpop) &lt;- ~Symptom/Tree
monpop</code></pre>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes
##    694 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      3 hierarchical levels - Tree Year Symptom
##      8 populations defined - BB_7 BB_26 FR_26 ... BB_79 FR_79 FR_45</code></pre>
</div>
<div id="clone-correction" class="section level2">
<h2>Clone correction</h2>
<p>When dealing wtih a clonal populations, analyses are typically conducted with and without clone corrections. Clone correction results in retaining only one individual per MLG. This technique is commonly used with the analysis of the index of association. Clone correction requires specification of the hierarchical levels at which clones should be censored.</p>
<p>Using <code>monpop</code> as an example, if we wanted to know the diversity of alleles within each tree per year, how should we go about correcting for the clones? We use the function <code>clonecorrect</code> specifying the “Tree/Year” hierarchy:</p>
<pre class="r"><code>mcc_TY &lt;- clonecorrect(monpop, hier = ~Tree/Year, keep = 1:2)
mcc_TY</code></pre>
<pre><code>## 
## This is a genclone object
## -------------------------
## Genotype information:
## 
##    264 multilocus genotypes
##    278 haploid individuals
##     13 codominant loci
## 
## Population information:
## 
##      3 hierarchical levels - Tree Year Symptom
##      6 populations defined - 7_9 26_9 26_10 45_10 79_10 26_11</code></pre>
<pre class="r"><code>setpop(monpop) &lt;- ~Tree/Year</code></pre>
<p>Now we can compare the diversity of alleles at each locus using Simpson’s index (<span class="math">\(1-D\)</span>):</p>
<pre class="r"><code>cc &lt;- locus_table(mcc_TY, info = FALSE)
mp &lt;- locus_table(monpop, info = FALSE)
mp - cc</code></pre>
<pre><code>##          summary
## locus     allele     1-D    Hexp Evenness
##   CHMFc4       .  0.0016  0.0024   0.0016
##   CHMFc5       . -0.0905 -0.1085  -0.0429
##   CHMFc12      .  0.0042  0.0064   0.0387
##   SEA          .  0.0312  0.0343   0.0851
##   SED          . -0.0739 -0.0832  -0.0756
##   SEE          . -0.0469 -0.0587  -0.0264
##   SEG          .  0.0320  0.0366   0.0482
##   SEI          . -0.0090 -0.0105   0.0306
##   SEL          . -0.0092 -0.0115  -0.0540
##   SEN          . -0.0501 -0.0563  -0.0764
##   SEP          .  0.0165  0.0188   0.0409
##   SEQ          . -0.0544 -0.0599  -0.0871
##   SER          . -0.0421 -0.0467  -0.0236
##   mean         . -0.0223 -0.0259  -0.0108</code></pre>
<p>We can see quite a difference in some alleles after clone correcting based on tree in the overall data set. Of course, we still want to analyze each tree/year combination separately. This is where it would help to construct a little function.</p>
<pre class="r"><code>plot_simp_diff &lt;- function(pop_name, mcc_TY, monpop){
  cc &lt;- locus_table(mcc_TY, pop = pop_name, info = FALSE)
  mp &lt;- locus_table(monpop, pop = pop_name, info = FALSE)
  res &lt;- mp - cc
  barplot(res[, &quot;1-D&quot;], main = pop_name)
}
pops &lt;- monpop@pop.names # Gather the population names
par(mfrow = c(2, 3)) # Set up the graphics to have two rows and three columns
for (i in pops){
  plot_simp_diff(i, mcc_TY, monpop)
}</code></pre>
<p><img src="C05_Population_Hierarchies_files/figure-html/unnamed-chunk-7.png" title="plot of chunk unnamed-chunk-7" alt="plot of chunk unnamed-chunk-7" width="960" /></p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<p>These barplots show the difference in Simpson’s index of original minus clone corrected data for each population per locus. We can see that allelic diversity generally is lower in the total data set (containing some repeated MLGs) relative to clone corrected data.</p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>This was a brief introduction to the easiest way to create hierarchical levels and apply them in <em>poppr</em> to more rapidly analyze your data. By indexing the hierarchical levels of your data, you can set the hierarchical level(s) you want to have analyzed in a single command line. This approach avoids having to create new sub-sets of the data for each analysis and simultaneously reduces the chance of error when manipulating data sets by hand.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<!-------->


<div class="references">
<p>Everhart S., Scherm H. 2014. Fine-scale genetic structure of <em>Monilinia fructicola</em> during brown rot epidemics within individual peach tree canopies. <em>Phytopathology</em> ##:submitted.</p>
</div>
</div>

</div>
</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with --self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "libs/mathjax-2.3.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
