```{r,message=FALSE,echo=FALSE}
  html <- TRUE
  library(knitcitations)
  bib <- read.bibtex("bibtexlib.bib")
  opts_chunk$set(tidy = FALSE, message = FALSE, warning = FALSE, 
                 fig.width = 10, fig.height = 6, cache = TRUE)
  if (html) opts_chunk$set(out.width = "700px", dpi = 300)
  # use this to set knitr options: 
  # http://yihui.name/knitr/options #chunk_options
```

---
title: '2: Data Preparation'
---

Introduction
----

Data Format
----

 - GenAlEx data
 - Others (FSTAT, Structure, Genetix, Genepop)
 - importing data frames with columns of data

Genotype Curve
----

 - monolinia data
 - microbov data
 
```{r}
library(poppr)
data(monpop)
mon.gc <- genotype_curve(monpop, quiet = TRUE)
```

```{r}
data(microbov)
mic.gc <- genotype_curve(microbov, quiet = TRUE)
barplot(microbov@loc.nall) # number of alleles per locus
mic10 <- microbov[loc = names(microbov@loc.nall[microbov@loc.nall < 11])] # At most 10 alleles/locus
mic10.gc <- genotype_curve(mic10, quiet = TRUE)
```

