
---
title: "Population genetics and genomics in R"
---

Welcome! This primer provides a concise introduction to conducting applied analyses of population genetic data in R, with a special emphasis on non-model populations including clonal or partially clonal organisms. It provides a valuable resource for tackling the nitty-gritty analysis of populations that do not necessarily conform to textbook genetics and might or might not be in Hardy-Weinberg equilibrium. While this primer does not require extensive knowledge of programming in R, the user is expected to install R and all packages required for this primer. 

We recently revised the primer substantially to include population genomic data, that is VCF data resulting from high-throughput sequencing of populations of either whole or reduced representation genomes. 

Please provide us feedback on any errors you might find or suggestions for improvement. The primer is currently published [here](http://grunwaldlab.github.io/Population_Genetics_in_R/).

*Niklaus J. Gr&uuml;nwald, Zhian N. Kamvar, Sydney E. Everhart, Javier F. Tabima, and Brian J. Knaus*
&copy; 2017, Corvallis, Oregon, USA

>*I was really impressed with what you've accomplished with [poppr], it is very thoughtful and addressed a number of things I never considered but which many pop gen folks that I know deal with all the time and complain about.  I think it is going to be very well received by the community.* 

-- Andy Jones, Assistant Professor, Oregon State University, Corvallis, OR, 2014.

